### ISSUE TITLE
Remove Dependency on io.zeebe.spring:java-common

### ISSUE THREAD

**Issue by grafvonb** [camunda-community-hub/camunda-tasklist-client-java#100]
Currently, the project has dependencies on these two JARs:
* api "io.camunda.spring:java-common:8.5.3"
* api "io.camunda:zeebe-client-java:8.5.3"

which causes issues due to the presence of the same Java types in the same packages (e.g., `Product`). 
![thumbnail_image008](https://github.com/user-attachments/assets/2224657d-89dd-4d6f-ad9e-7ed4702ab507)

According to @jonathanlukas , "io.camunda:zeebe-client-java" was originally intended to be part of an SDK, but it is no longer relevant. 

Please move the relevant types to the SDK and remove this dependency from the Tasklist client.

**Comment by npolovnikov** [comment]
Do you have any local fast solution on this?
I wanna you last version on camunda and i need some tasklist-client
