### ISSUE TITLE
Will this get merged with spring-zeebe?

### ISSUE THREAD

**Issue by jphillips-bp3** [camunda-community-hub/camunda-tasklist-client-java#109]
Given that Spring Zeebe (https://github.com/camunda-community-hub/spring-zeebe) has a "native" Operate client that can be autowired, will there be a time when this Tasklist Client be made part of the Spring Zeebe in the same way?

**Comment by jonathanlukas** [comment]
As spring-zeebe will be archived soon, this project will remain intact.

**Comment by jphillips-bp3** [comment]
> As spring-zeebe will be archived soon, this project will remain intact.

Thanks. What will spring-zeebe be replaced by?.

**Comment by jonathanlukas** [comment]
The deprecation notice here will redirect you to the according projects: https://github.com/camunda-community-hub/spring-zeebe
