### ISSUE TITLE
Maintained release versions

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/camunda-tasklist-client-java#123]
Right now, we only release from the `main` branch.

Should we also release from a `release/8.5` and `release/8.6` branch and make the main branch a development branch only?

**Comment by chDame** [comment]
100% agree

**Comment by jonathanlukas** [comment]
Cool, I will go ahead and set up a release branch accordingly. Will be comparable to https://github.com/camunda-community-hub/camunda-operate-client-java

**Comment by jonathanlukas** [comment]
Done
