### ISSUE TITLE
Http request failed with status code `405`

### ISSUE THREAD

**Issue by mohammad1111** [camunda-community-hub/camunda-tasklist-client-java#13]
hi

all request to taskList service, raise this  error :

io.camunda.tasklist.exception.TaskListException: com.apollographql.apollo3.exception.ApolloHttpException: Http request failed with status code `405`

for example,  i use this code : 
```
   CamundaTaskListClient client = new CamundaTaskListClient.Builder().taskListUrl("http://localhost:8081").shouldReturnVariables().authentication(sa).build();
        var task=client.getAssigneeTasks("demo", TaskState.CREATED,10);

```

![image](https://user-images.githubusercontent.com/3103304/211508199-d25d92f3-dbc0-4853-8bcc-276cfe4777bd.png)

**Comment by mohammad1111** [comment]
> hi
> 
> all request to taskList service, raise this error :
> 
> io.camunda.tasklist.exception.TaskListException: com.apollographql.apollo3.exception.ApolloHttpException: Http request failed with status code `405`
> 
> for example, i use this code :
> 
> ```
>    CamundaTaskListClient client = new CamundaTaskListClient.Builder().taskListUrl("http://localhost:8081").shouldReturnVariables().authentication(sa).build();
>         var task=client.getAssigneeTasks("demo", TaskState.CREATED,10);
> ```
> 
> ![image](https://user-images.githubusercontent.com/3103304/211508199-d25d92f3-dbc0-4853-8bcc-276cfe4777bd.png)

resolved my problem with replace   SimpleAuthentication with    SelfManagedAuthentication.

thanks camunda.

**Comment by chDame** [comment]
Hi Mohammad, glad you found the solution :)
