### ISSUE TITLE
Project example for camunda-tasklist-client-java

### ISSUE THREAD

**Issue by volodya327** [camunda-community-hub/camunda-tasklist-client-java#15]
Hi, this is not an issue. Just a proposition.
Could you share, please, your simple Project example for camunda-tasklist-client-java ?
Only one simple HTML page with java code example which can be run.

**Comment by chDame** [comment]
Hi Volodya,

Do you think something is missing from the readme ?

**Comment by volodya327** [comment]
Hi Christophe,
Your readme looks nice. But I think, it will be usefull to add a small example for easy start using tasklist client. Like in [spring-zeebe](https://github.com/camunda-community-hub/spring-zeebe) client. Inside of [example](https://github.com/camunda-community-hub/spring-zeebe/tree/master/example) folder.
One working example can be better then millions of words. I would appreciate it. And maybe not only me.

**Comment by volodya327** [comment]
Hi Christophe,
Could you, please, verify the example of using SelfManagedAuthentication in readme (section "Authentication"):
`SelfManagedAuthentication sma = new SelfManagedAuthentication().clientId("java").clientSecret("foTPogjlI0hidwbDZcYFWzmU8FOQwLx0").baseUrl("http://localhost:18080").keycloakRealm("camunda-platform");`
Maybe it will be correct to use .keycloakUrl() insted of .baseUrl() ?
