### ISSUE TITLE
processDefinitionId returns "Process Instance Key"

### ISSUE THREAD

**Issue by volodya327** [camunda-community-hub/camunda-tasklist-client-java#19]
Hi Christophe,
When I try to get processDefinitionId, I receive a number that looks like "Process Instance Key" from another Instance.

<img width="950" alt="processDefinitionId_Error" src="https://user-images.githubusercontent.com/43142528/217303972-59bfae09-28ca-413c-9904-1f37821a64cd.png">

**Comment by chDame** [comment]
Hi Volodya,

If you check with Operate APIs, you will see that this definitionId is the good one.

**Comment by volodya327** [comment]
Hello Christophe, 

When I see a "Process Id" in Modeler, it has a string like "Process_107v1hv", but processDefinitionId in Tasklist Client containes "2251799816697009". I think, this is not Ok.
But if you think it's all right, then how to get real processDefinitionId ("Process_107v1hv") ?
P.S. taskDefinitionId in Tasklist Client is realy Ok.
<img width="775" alt="processDefinitionId_Error2" src="https://user-images.githubusercontent.com/43142528/217759061-70bf1884-9ace-4cc6-a23c-7fb74f2d0307.png">
