### ISSUE TITLE
getAssigneeTasks got  Use JsonReader.setLenient(true) to accept malformed JSON at path 

### ISSUE THREAD

**Issue by dahang** [camunda-community-hub/camunda-tasklist-client-java#20]
when call  TaskList getAssigneeTasks(String assigneeId, TaskState state, Integer pageSize)

inside  
result = Rx3Apollo.single(call).blockingGet();

got this  JsonEncodingException "com.apollographql.apollo3.exception.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path "

please advise I am using version 1.6.1 and  Camunda is 8.1.6

**Comment by chDame** [comment]
Hi @dahang,

Sorry for the late reply but I'm pretty busy these last weeks/months. You should check if you provided the correct authentication and the correct url. What Apollo is saying is that it didn't get a JSON as a response.

**Comment by chDame** [comment]
not used anymore
