### ISSUE TITLE
Add processInstanceId from TaskQuery API Version: 8.1

### ISSUE THREAD

**Issue by volodya327** [camunda-community-hub/camunda-tasklist-client-java#23]
Hi Christophe,
Could you add, please, **processInstanceId** to tasklist client params as it presents in TaskQuery API Version: 8.1:
[https://docs.camunda.io/docs/apis-clients/tasklist-api/inputs/task-query/](https://docs.camunda.io/docs/apis-clients/tasklist-api/inputs/task-query/)
Thanks !

**Comment by mykhailo-smyrnov** [comment]
Hi @chDame,
I also faced with same issue.
**processInstanceId** is really required.
Because I do not see another way how to join process instance and tasks related to.
It will be so helpful.
Thank you!

**Comment by chDame** [comment]
Hi @mykhailo-smyrnov @volodya327,

I'm very busy these last weeks but should have some time next week to look into it. If that's urgent, feel free to open a PR that I'll try to review asap. If not, we should have a new version before end of next week

**Comment by mykhailo-smyrnov** [comment]
Hi @chDame 

Thank you for the reply.
That's not urgent for me.
I'm calling GraphQL API for _get tasks_ directly so it works fine.
But do not want to fall in love with legacy.

**Comment by volodya327** [comment]
Thanks, Christophe, I'll wait the new version from you.
Have a nice day !

**Comment by chDame** [comment]
Hi @volodya327 @mykhailo-smyrnov 

The release 1.6.2 comes with the possibility to filter on process instance id, task definition id and process definition id. It's available in the TaskSearch object :
```
TaskSearch ts = new TaskSearch().setProcessInstanceId("2251799818839086");
 client.getTasks(ts);
```
I also added a new getTasks method that takes these 3 parameters getTasks(String group, Boolean assigned, String assigneeId, TaskState state, **String processDefinitionId, String processInstanceId, String taskDefinitionId**, boolean withVariables, Pagination pagination).
The former version of this method is still available and will set these parameters as null values : getTasks(String group, Boolean assigned, String assigneeId, TaskState state, boolean withVariables, Pagination pagination)

Hope that helps. Please confirm if that fully solves your issue and if we can close this ticket :)

**Comment by volodya327** [comment]
Hi Christophe,
Thanks for you quick work. I need also a method, which will return the processInstanceId for the current task. Something like: task.getProcessInstanceId(). 
Is it possible to add it to camunda-tasklist-client-java ?

P.S. As I can see, it's 8.2 version now and Camunda unexpectedly migrating from GraphQL to REST API. We live in an era of change... 8-)

**Comment by mykhailo-smyrnov** [comment]
@chDame Thank you for the quick update. 1.6.2 works fine.

**Comment by mykhailo-smyrnov** [comment]
@chDame 8.2 version looks better. Hope you implement it soon. Looking forward for that :-)

**Comment by chDame** [comment]
> Hi Christophe, Thanks for you quick work. I need also a method, which will return the processInstanceId for the current task. Something like: task.getProcessInstanceId(). Is it possible to add it to camunda-tasklist-client-java ?
> 
> P.S. As I can see, it's 8.2 version now and Camunda unexpectedly migrating from GraphQL to REST API. We live in an era of change... 8-)

Yes, indeed this will make this client soon deprecated and bring the possibility to create a new one that will bring less dependencies (as the operate client)

**Comment by mykhailo-smyrnov** [comment]
@chDame @volodya327 
sorry to bore you but is anybody know how to update task variable?
I see only complete task api but not just update variable.
is it possible?

**Comment by falko** [comment]
> how to update task variable? I see only complete task api but not just update variable. is it possible?

@mykhailo-smyrnov setting variables is possible through the [Zeebe gRPC API](https://docs.camunda.io/docs/next/apis-tools/grpc/#setvariables-rpc), e.g. using the [Zeebe Java Client](https://docs.camunda.io/docs/next/apis-tools/java-client/).

**Comment by mykhailo-smyrnov** [comment]
@falko it's worked for me. Thank you!
But one more question - how to delete variable? :-)

**Comment by volodya327** [comment]
@mykhailo-smyrnov I'm not sure this is possible to delete process variable. Anyway, you can ask your question on [forum.camunda.io](https://forum.camunda.io/c/camunda-platform-8-topics)
