### ISSUE TITLE
Support for claimTask.allowOverrideAssignment

### ISSUE THREAD

**Issue by angelo-v** [camunda-community-hub/camunda-tasklist-client-java#24]
The GraphQL API supports a parameter `allowOverrideAssignment` in the `claimTask` mutation, that is not available in the Java Client yet. Please add it as an optional parameter to the `CamundaTaskListClient.claim` method

**Comment by chDame** [comment]
Hi @angelo-v,

I'll try to look into it next week. If you want it earlier, please feel free to open a PR :)

**Comment by chDame** [comment]
Hi @angelo-v,

This is available in 1.6.2 and you now ave 2 claims method. One with allowOverrideAssignment and the other one without (default value will be false). Hope that helps! Tell me if I can close the ticket after your tests. Thanks :)

**Comment by angelo-v** [comment]
Thank you very much for the quick response, this is helpful
