### ISSUE TITLE
While trying to fetch tasks of process instances ,at this line use client.getTasks() getting error

### ISSUE THREAD

**Issue by neha119** [camunda-community-hub/camunda-tasklist-client-java#25]
I am using camunda 8.1 and camunda-tasklist-client Library mentioned in this example.
When i run the project it shows error at this statement
Client.getTasks(ts).
Error : 
io.camunda.tasklist.exception.TaskListException:Error(message=Validation error of type wrongtype argument query with value 'ObjectValue{objectfields{objectfields=candidategroup, assignee, assigned,state,processDefinitionId,processInstanceId,pagesize,search after,search before,contains a filed not in Taskquery : processDefinitionId @ tasks

My need is to create rest api that pass the process instance id and fetch the tasks associated with it.
But using this example I am not able to get.

Please help.

**Comment by SayaliJadhav21** [comment]
I am also facing the same issue.

**Comment by chDame** [comment]
Hi @neha119, @SayaliJadhav21,

What do the TaskSearch look like ? I just tried that code against a 8.1.7 and got my tasks:
```
TaskSearch ts = new TaskSearch().setProcessDefinitionId("2251799816253313");
client.getTasks(ts);
```

Also, it's worth mentioning that since 8.2, tasklist also offers Rest API and the GraphQL endpoints will be deprecated (and this library also).

**Comment by btamega-neoxia** [comment]
> Hi @neha119, @SayaliJadhav21,
> 
> What do the TaskSearch look like ? I just tried that code against a 8.1.7 and got my tasks:
> 
> ```
> TaskSearch ts = new TaskSearch().setProcessDefinitionId("2251799816253313");
> client.getTasks(ts);
> ```
> 
> Also, it's worth mentioning that since 8.2, tasklist also offers Rest API and the GraphQL endpoints will be deprecated (and this library also).

But it doesn't work against 8.1.6 or the documentation mentionned that processDefinitionId is present since 8.1

**Comment by avx99** [comment]
I am facing the same issue for camunda 8.1.6

**Comment by chDame** [comment]
no response
