### ISSUE TITLE
Pagination , what to do for getting second page of task list using Pagination

### ISSUE THREAD

**Issue by akashkarunk** [camunda-community-hub/camunda-tasklist-client-java#26]
if i am considering 1 page with 10 tasks , how can I get the second page
taskListClient.getGroupTasks("groupName" , TaskState.CREATED, 10),
Please help

**Comment by chDame** [comment]
Hi @akashkarunk,

you can use the after method : 
TaskList firstPage= taskListClient.getGroupTasks("groupName" , TaskState.CREATED, 10);
TaskList secondPage = taskListClient.after(firstPage);

The example is provided in the README.

**Comment by akashkarunk** [comment]
Thank you @chDame
