### ISSUE TITLE
Get camunda Candidate Users task

### ISSUE THREAD

**Issue by akashkarunk** [camunda-community-hub/camunda-tasklist-client-java#28]
![image](https://github.com/camunda-community-hub/camunda-tasklist-client-java/assets/101084681/18108391-fa12-4035-afb5-be4f26acf98d)

I have added candidate users and it is assigned to task , is there a way to fetch candidate user task from tasklist-client? tried by both getGroupTasks and getAssigneeTasks both were not working

**Comment by akashkarunk** [comment]
Can someone help

**Comment by chDame** [comment]
Hi @akashkarunk,

I'll try to add these feature soon. But if you're using a 8.2, I would suggest using the rest apis rather than this client.

**Comment by chDame** [comment]
Hi @akashkarunk,

a release 1.7.0 is on his way and it provide some more TaskSearch attributes : candidateUser, dueDate, followUpDate.

Again, I would strongly advise to switch to rest apis soon!

**Comment by chDame** [comment]
Hi @akashkarunk,

The 1.7.0 is released and should solve your issue:
```
TaskSearch ts = new TaskSearch().setCandidateUser("michel");
client.getTasks(ts);
```

**Comment by chDame** [comment]
yes they are going to be soon richer than the graphQL apis. If I have some time, I will look to generate a rest client based on the open apis (if noone does it before me :))

**Comment by akashkarunk** [comment]
Ok Thank you

**Comment by akashkarunk** [comment]
Hi @chDame , Are you having any reference for this rest api implementation on tasklist.
