### ISSUE TITLE
Bug: TaskListClient does not fetche task variables when withVariables is set to true

### ISSUE THREAD

**Issue by sam0r040** [camunda-community-hub/camunda-tasklist-client-java#32]
Hi, 

we just upgraded to version 8.3.1.1 and noticed that there is a bug when fetching tasklist variables. The TaskListClient should fetch task variables when withVariables is set to true. Unfortunately the logic seems to be flipped as the TaskListClient only fetches the variables when withVariables is set to false.

The reason being:
```
if (!withVariables) {
     variables = taskApi.searchTaskVariables(taskId, new VariablesSearchRequest());
 }
```

**Comment by chDame** [comment]
Hi @sam0r040,

Thanks, I'll fix it today!

**Comment by sam0r040** [comment]
Can you already say if you will provide a bugfix release soon or will it take some time?

**Comment by chDame** [comment]
I'll fix it and release it today!

**Comment by sam0r040** [comment]
Oh thats great, thanks!

**Comment by chDame** [comment]
Hi @sam0r040,

Version 8.3.1.2 has been released and is available in maven central and should fix the issue! I'll let you close the issue once you have tested it

Thanks again

**Comment by sam0r040** [comment]
Issue is fixed, thanks for the really quick bugfix :)
