### ISSUE TITLE
【BUG】io.camunda.spring:java-common is too old

### ISSUE THREAD

**Issue by KricYi** [camunda-community-hub/camunda-tasklist-client-java#57]
`JwtConfig jwtConfig = new JwtConfig();`
`jwtConfig.addProduct(Product.TASKLIST, new JwtCredential("clientId", "clientSecret", null, "keycloakUrl"));`
`Authentication auth = SelfManagedAuthentication.builder().jwtConfig(jwtConfig).keycloakUrl("keycloakUrl").build();`
`CamundaTaskListClient camundaTaskListClient = CamundaTaskListClient.builder().taskListUrl("taskListUrl").shouldReturnVariables().shouldLoadTruncatedVariables().authentication(auth).build();`

**Comment by KricYi** [comment]
`SimpleConfig simpleConfig = new SimpleConfig();`
       ` simpleConfig.addProduct(Product.TASKLIST,new SimpleCredential("demo","demo"));`
        `Authentication auth =SimpleAuthentication.builder().simpleUrl("tasklistUrl").simpleConfig(simpleConfig).build();`
        `CamundaTaskListClient camundaTaskListClient = CamundaTaskListClient.builder().taskListUrl("tasklistUrl").shouldReturnVariables().shouldLoadTruncatedVariables().authentication(auth).build();`

**Comment by chDame** [comment]
related to https://github.com/camunda-community-hub/spring-zeebe/issues/684
