### ISSUE TITLE
Issue while Authentication in SaaS and Self-Managed 

### ISSUE THREAD

**Issue by ikomalchauhan** [camunda-community-hub/camunda-tasklist-client-java#6]
Hi Team, Thank you so much for creating the wonderful lib. Its really helpful for the automation process.
I'm facing issue while authentication through self managed as I am receiving multiple 'Set-Cookie'. Also in SaaS authentication its giving me NullPointerException as I provide credentialId and credentialSecret from the console.
Can you guide me on this.

**Comment by chDame** [comment]
Hi @ikomalchauhan,

Could you tell me the version you're using as well as the source code associated ? (without sharing clientId or secret)?

I'll try to reproduce locally.

**Comment by chDame** [comment]
Hi @ikomalchauhan,

I've released a new version 1.0.6 that is not relaying on any external library for the authentication. Perhaps you could try and tell me how it goes ?

**Comment by ikomalchauhan** [comment]
Hi @chDame,

Thanks for connecting. Please find attachments containing the problem.

![auth-error](https://user-images.githubusercontent.com/76562738/175925192-9bb08e71-9bdd-4518-9775-0a879fdbeb25.png)
![auth-error-2](https://user-images.githubusercontent.com/76562738/175925446-955600d0-8158-4913-867c-15525438e1a7.png)

while implementing:
```
public CamundaTaskListClient getTasklistClient(String username, String password) {
		CamundaTaskListClient client = null;

		SaasAuthentication sa = new SaasAuthentication(username, password);

		try {
			client = new CamundaTaskListClient.Builder().authentication(sa)
					.taskListUrl("https://bru-2.tasklist.camunda.io/72e69da7-2d7d-4266-bf2c-f73b836c2164/").build();
			
			return client;
		} catch (TaskListException e) {
			e.printStackTrace();
		}
		return client;
	}
```

**Comment by chDame** [comment]
Hi @ikomalchauhan,

A 404 means that you can't access to https://login.cloud.camunda.io/oauth/token. This URL is publicly accessible and you should certainly look at your network. Could you have a proxy or a firewall blocking it ?

**Comment by chDame** [comment]
Could you tell me what is the Camunda version you're using locally? I've tried this client with versions from 8.0.0 to 8.0.3. The error seems to indicate that the graphQL library (apollo) isn't able to read the server response. Could it be that you use some older version ? Or could it be that authentication failed and you're getting an html response instead of the graphql ?

**Comment by chDame** [comment]
Since there is no more activity, do you want to close this issue ?

**Comment by ikomalchauhan** [comment]
Thanks Christophe Dame for the help
