### ISSUE TITLE
User Task claim isssue - allowOverrideAssignment

### ISSUE THREAD

**Issue by michals96** [camunda-community-hub/camunda-tasklist-client-java#69]
Hey guys.

Just trying to claim a task that was already claimed (without unclaiming). I would expect that including `allowOverrideAssignment` as `true` would make it possible.

However an exception is being thrown with this message:
```
Error(message = Task is already assigned, locations = [Location(line = 1, column = 91)], path=[claimTask], extensions = {type=InvalidRequestException, classification=DataFetchingException}, nonStandardFields = null)
```

Is it possible that there is sa bug? For reference, I found a smiliar issue being reported in the forum lately.
https://forum.camunda.io/t/task-is-already-assigned/51100/2

**Comment by chDame** [comment]
Hi @michals96,

The client code seems clean but I'll try to have a look at it today to check if there is an issue at the api level. What is your version of tasklist client and the version of your camunda platform ?

**Comment by michals96** [comment]
I noticed the issue with tasklist client version 1.7.0 and 8.3.0.

Locally running it with zeebe 8.3.0-alpha4 and tasklist 8.3.0-alpha4.

**Comment by chDame** [comment]
Hi Michals, I found the internal ticket that was open. The problem is that this attribute can only be used when connected through jwt token (M2M).

**Comment by michals96** [comment]
Ok, cool, thank you @chDame :) 

Then I guess the easiest way to achieve that without M2M for now is to unclaim first, before claiming :)
