### ISSUE TITLE
Filter by nested process variables

### ISSUE THREAD

**Issue by aowss** [camunda-community-hub/camunda-tasklist-client-java#78]
Hi,
is it possible to fetch a set of tasks based on a nested process variable?
Let's assume that my process variables are as follows:

```json
{
  "order" {
    "orderId": "4425d148-a2a6-4b78-b42f-43f983adc131"
  }
}
```

Can I do `searchCriteria.addVariableFilter("order.orderId", "4425d148-a2a6-4b78-b42f-43f983adc131");`?
If not, how can I do that?

**Comment by chDame** [comment]
Hi @aowss,

Did you try new TaskSearch().addVariableFilter("order", Map.of("orderId", "4425d148-a2a6-4b78-b42f-43f983adc131"))?

**Comment by bl4ckp4nther** [comment]
@aowss what if order has more attributes, like quantity etc... Will 
`new TaskSearch().addVariableFilter("order", Map.of("orderId", "4425d148-a2a6-4b78-b42f-43f983adc131"))` still work?

**Comment by chDame** [comment]
Hi @bl4ckp4nther,

No it's not working, the backend API only allow to search on exact match. I tried to search on order.orderId instead but that's also not supported because the index is built on the whole variable.

**Comment by jonathanlukas** [comment]
To achieve this, please open a feature request in camunda/camunda
