### ISSUE TITLE
Update GitHub deployment Action

### ISSUE THREAD

**Issue by xomiamoore** [camunda-community-hub/camunda-tasklist-client-java#86]
Hello! We had to make a few changes to our community's Maven deployment Action. Specifically, we updated the secret names and deployment credentials.

Please update to [the latest release, v. 1.2.1](https://github.com/camunda-community-hub/community-action-maven-release/releases/tag/v1.2.1), to make sure your Action works. Thank you!

**Comment by chDame** [comment]
Hi @xomiamoore,

Many thanks for raising these updates. I've updated the actions and a new released has been successfully published. Have a great day!
