### ISSUE TITLE
Incorrect example for SelfManagedAuthentication

### ISSUE THREAD

**Issue by jancalvef** [camunda-community-hub/camunda-tasklist-client-java#88]
When we follow example from the README:
<img width="862" alt="image" src="https://github.com/camunda-community-hub/camunda-tasklist-client-java/assets/121793098/0741b445-fb51-46db-af6a-07ac6ad76708">

we get:
![image](https://github.com/camunda-community-hub/camunda-tasklist-client-java/assets/121793098/a69604fb-631f-4a96-a0db-18e99515cb2a)

We're using the latest (8.5.0) version of the TaskList Client. From the looks of it we'll have to specify an IdentityConfig as well?

**Comment by chDame** [comment]
Hi @jancalvef,

Thanks for raising the issue. The authentication mechanism is coming from https://github.com/camunda-community-hub/spring-zeebe/tree/main/camunda-sdk-java/java-common and may change without this README being update :/

To make it easier, I've change the README to promote the helpers we introduced in the client builder and that encapsulate the "auth soup".

Thanks again!
