### ISSUE TITLE
com.apollographql.apollo3.exception.ApolloHttpException: Http request failed with status code 401

### ISSUE THREAD

**Issue by AmruthaMotamarry** [camunda-community-hub/camunda-tasklist-client-java#9]
Hi @chDame 
I’m utilizing SelfManagedAuthentication provided by Camunda to create tasklist client. After installing the helm chart which includes spring jwt tokens environment variables, client is not authenticating as shown below.

io.camunda.tasklist.exception.TaskListException: com.apollographql.apollo3.exception.ApolloHttpException: Http request failed with status code 401
at io.camunda.tasklist.CamundaTaskListClient.execute(CamundaTaskListClient.java:138)
at io.camunda.tasklist.CamundaTaskListClient.getTasks(CamundaTaskListClient.java:116)
at io.camunda.tasklist.CamundaTaskListClient.getTasks(CamundaTaskListClient.java:62)
at io.camunda.tasklist.CamundaTaskListClient.getTasks(CamundaTaskListClient.java:57)
Caused by: com.apollographql.apollo3.exception.ApolloHttpException: Http request failed with status code 401

It would be helpful if you could state any configurations that I’m missing. Thanks in advance.

**Comment by chDame** [comment]
Hi @AmruthaMotamarry,

Error 401 means no authorization. Did you create your application in identity with operate read/write permissions ?

**Comment by AmruthaMotamarry** [comment]
Hi @chDame 

Yes, created the application in identity and assigned read/write permissions.

**Comment by AmruthaMotamarry** [comment]
SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI and SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI 

after adding these two variables, facing 401 in tasklist, operate, optimize. It would be helpful if you could help in resolving this issue

**Comment by chDame** [comment]
Hi @AmruthaMotamarry,

First step will be to reproduce with postman (or equivalent) :
execute a POST to ${yourkeycloakUrl}/auth/realms/camunda-platform/protocol/openid-connect/token
with params ( x-www-form-urlencoded): grant_type=client_credentials&client_id=${clientId}&client_secret=${clientSecret}

retrieve the access_token from the response and then execute a query against your tasklist ${tasklist}/graphql
payload:
{"operationName":"GetTasks","variables":{"state":"CREATED","pageSize":50},"query":"query GetTasks($assignee: String, $assigned: Boolean, $state: TaskState, $pageSize: Int, $searchAfter: [String!], $searchBefore: [String!], $searchAfterOrEqual: [String!]) {\n  tasks(\n    query: {assignee: $assignee, assigned: $assigned, state: $state, pageSize: $pageSize, searchAfter: $searchAfter, searchBefore: $searchBefore, searchAfterOrEqual: $searchAfterOrEqual}\n  ) {\n    id\n    name\n    processName\n    assignee\n    creationTime\n    taskState\n    sortValues\n    isFirst\n    __typename\n  }\n}"}

with the authentication header : Authorization : Bearer ${access_token}

What is the response you get ?

**Comment by AmruthaMotamarry** [comment]
Hi @chDame 

Executed the same as you mentioned with the authorization header in postman. Facing 401 unauthorized with message "the provided claims are invalid"

**Comment by chDame** [comment]
what version of Camunda are you using ?

**Comment by AmruthaMotamarry** [comment]
we have installed 8.1.2 recently

**Comment by chDame** [comment]
I'll try to reproduce. Are you sure you managed permissions as documented here ?https://docs.camunda.io/docs/next/self-managed/identity/user-guide/assigning-a-permission-to-an-application/

**Comment by AmruthaMotamarry** [comment]
Hi @chDame,

Thank you so much. The issue for tasklist is resolved but in operate we are still facing the issue.
