### ISSUE TITLE
Candidate Group, Candidate Groups Issue in tasklist java Client version 8.5

### ISSUE THREAD

**Issue by MohamedAhmed412000** [camunda-community-hub/camunda-tasklist-client-java#94]
The conversion from TaskSearch Class to TaskSearchRequest Class not completed successfully
It passes always the parameters candidateGroup, candidateGroups with null values
I tried these versions 8.5.0, 8.5.3, 8.5.3.1, 8.5.3.2, 8.5.3.3
I am using Keyclock to authenticate with Identity

![image](https://github.com/camunda-community-hub/camunda-tasklist-client-java/assets/50495610/fa69d25b-efec-438a-ad01-905a9e247d1e)

**Comment by chDame** [comment]
Hi @MohamedAhmed412000,

Thanks for reporting. You're right! The problem comes from the attributes names that changed. I'll check other properties and release a patched version. I'll keep you posted today.

**Comment by chDame** [comment]
Could you tell me if version 8.5.3.4 fix your issue ?

**Comment by MohamedAhmed412000** [comment]
Hi @chDame 

Thanks for your fast response
I tried the version 8.5.3.4 & Yes It fixes the problem
