### ISSUE TITLE
Can not find Product

### ISSUE THREAD

**Issue by AlexYangYu** [camunda-community-hub/camunda-tasklist-client-java#95]
backgroud:
SpringBoot3.3 + Camund8.5

dependency:
    implementation group: 'io.camunda.spring', name: 'spring-boot-starter-camunda', version: '8.5.7'

    implementation group: 'io.camunda', name: 'camunda-tasklist-client-java', version: '8.5.3.4'

code:
```java
SimpleConfig simpleConf = new SimpleConfig();
simpleConf.addProduct(Product.TASKLIST, new SimpleCredential("user", "pwd", "http://tasklistUrl[:port]"));
Authentication auth = SimpleAuthentication.builder().withSimpleConfig(simpleConf).build();

CamundaTaskListClient client = CamundaTaskListClient.builder()
  .taskListUrl("http://tasklistUrl[:port]")
  .authentication(auth)
  .cookieExpiration(Duration.ofSeconds(5))
  .build();
```
The above code will prompt that Product cannot be found. How to solve?

**Comment by chDame** [comment]
Hi @AlexYangYu ,

import io.camunda.common.auth.Product;

**Comment by rashidRizvi98** [comment]
I am using keycloak to authenticate in a self managed cluster. 
 
    @Bean
    public CamundaTaskListClient client() throws TaskListException{
        return CamundaTaskListClient.builder()
        .taskListUrl(taskListUrl)
        .selfManagedAuthentication(taskListClientId, taskListClientSecret, keycloakUrl)
        .build();
    }
    
    For me also it is throwing a compilation error
    
    Caused by: java.lang.NoSuchFieldError: Class io.camunda.common.auth.Product does not have member field 'io.camunda.common.auth.Product TASKLIST'

**Comment by chDame** [comment]
Could you try adding the identity repository as described here : https://forum.camunda.io/t/the-following-artifacts-could-not-be-resolved-io-camundajar-8-3-1/48486

**Comment by rashidRizvi98** [comment]
Seems some dependency version mismatch was causing this issue.  I was using below dependency(for zeebe) from camunda documentation.

```
<dependency>
           <groupId>io.camunda</groupId>
           <artifactId>spring-boot-starter-camunda-sdk</artifactId>
           <version>8.5.0</version>
  </dependency> 
```
After removing it worked
