### ISSUE TITLE
Configuration for a self-signed SSL certificate

### ISSUE THREAD

**Issue by mmaslarova** [camunda-community-hub/camunda-tasklist-client-java#96]
Hello, 

first of all, many thanks for the Client Library! It is really helpful for us Camunda users.

I would like to ask a question about HTTPS/SSL support. I hope this is the correct way to ask a question, I couldn't find another way.

Is there the possibility to configure the library to connect to a Tasklist API which is secured via a self-signed SSL certificate? 

I am looking for something similar to [ZeebeClientBuilder#caCertificatePath](https://javadoc.io/static/io.camunda/zeebe-client-java/8.5.0/io/camunda/zeebe/client/ZeebeClientBuilder.html#caCertificatePath(java.lang.String)).
I would like to use the same self-signed certificate for both the Zeebe and Tasklist APIs. And thus configure both client libs - for Zeebe and Tasklist, to trust the self-signed certificate.

Many thanks and kind regards,
mmaslarova

**Comment by chDame** [comment]
Hi @mmaslarova,

There is not such mechanism in this client for now. You would need to add your certificate in your truststore or add a custom truststore to the application using this client.

But it could be a nice feature in the future. I'll have no time to work on this for now but feel free to add a contribution in a PR. Or I'll handle it when I have more bandwidth :)

**Comment by mmaslarova** [comment]
Hi @chDame ,

Many thanks for your response. 

Sorry, what exactly do you refer to by saying the following?
> or add a custom truststore to the application using this client.

**Comment by jonathanlukas** [comment]
https://www.baeldung.com/java-custom-truststore
