### ISSUE TITLE
complete task

### ISSUE THREAD

**Issue by Xlt3h** [camunda-community-hub/camunda-tasklist-client-java#97]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "io.camunda.tasklist.dto.Task$Implementation.equals(Object)" because the return value of "io.camunda.tasklist.dto.Task.getImplementation()" is null] with root cause

java.lang.NullPointerException: Cannot invoke "io.camunda.tasklist.dto.Task$Implementation.equals(Object)" because the return value of "io.camunda.tasklist.dto.Task.getImplementation()" is null
        at io.camunda.tasklist.CamundaTaskListClient.completeTask(CamundaTaskListClient.java:107)

**Comment by chDame** [comment]
Hi @Xlt3h,

What's you C8 cluster version and client version ?

**Comment by Xlt3h** [comment]
i am running self managed and i dont have or know what cluster version is  but here is my pom file and my client version is 8.5.3.4 and  <properties>
		<java.version>21</java.version>
		<spring-boot.version>3.2.3</spring-boot.version>
		<zeebe.version>8.5.3</zeebe.version>
		<spring-zeebe.version>8.5.3</spring-zeebe.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<version.connector-http-json>8.5.4</version.connector-http-json>
		<version.connector-sqs>0.20.2</version.connector-sqs>
	</properties>
