### ISSUE TITLE
Impossible to use the SimpleAuthentication

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-community-hub/camunda-tasklist-client-java#98]
I'm a little confused.

My application will used camunda-tasklist-client-java: 8.5.3.4 and java-client-operate:8.5.8-rc1

In the taskList client, the SimpleAuthentication say

`Authentication auth = SimpleAuthentication.builder().withSimpleConfig(simpleConf).build();
`
According to CamundaTaskListClientBuilder, there is an
` import io.camunda.common.auth.Authentication;`

But io.camunda.common is not part of the library. Where is this class supposed to be?
The problem is this class exist in the library **java-client-operate:8.5.8-rc1**
(I am not sure if it is a coincidence or not) and it's deprecated there. And here, there is no "**SimpleAuthentication**" class with a builder. There is an **io.camunda.operate.auth.SimpleAuthentication**, but implement the interface **io.camunda.operate.auth.Authentication**

So,  it's not possible to compile the example.
Is that a bug? Where is the  **io.camunda.common.auth.Authentication** ?

It would be awesome if the two libraries has the same structure
* name
* connection method (library should onboard an ip.camunda.tasklist.auth)

**Comment by chDame** [comment]
Hi PY,

No, the tasklistclient is depending on the camunda common. You may use the helpers for SaaS and Self Managed (as documented in the readme) but the simple one is this one :
io.camunda.common.auth.SimpleAuthentication

Best regards,

Christophe
